# fly.toml file generated for tori-tracker on 2023-03-15T03:05:40+02:00

app = "tori-tracker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

[[services.ports]]
  handlers = ["pg_tls"]
  port = 5432

[env]
